name: Flutter Build APK

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'  # Only trigger when files in app/ directory change
  workflow_dispatch:  # Allow manual trigger
    inputs:
      version_tag:
        description: 'Version tag (e.g., 1.2.3456)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'  
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
        
    - name: Get dependencies
      working-directory: ./app
      run: flutter pub get
  
    - name: Create local.properties
      working-directory: ./app/android
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "flutter.sdk=$FLUTTER_ROOT" >> local.properties
        echo "googleMapsApiKey=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> local.properties
        echo "imgbbApiKey=${{ secrets.IMGBB_API_KEY }}" >> local.properties

    # - name: Run tests (optional)
    #   working-directory: ./app
    #   run: flutter test
      
    - name: Build APK
      working-directory: ./app
      run: flutter build apk --release
      
    - name: Get commit message
      id: commit
      run: echo "message=$(git log --format=%B -n 1 ${{ github.sha }} | head -n 1)" >> $GITHUB_OUTPUT
      
    - name: Set version tag
      id: version
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "tag=${{ github.event.inputs.version_tag }}" >> $GITHUB_OUTPUT
        else
          # Generate automatic version based on timestamp or commit short hash
          echo "tag=$(date +%Y.%m.%d)-$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
        fi
        
    - name: Set build date
      id: build_date
      run: echo "date=$(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_OUTPUT
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-${{ steps.version.outputs.tag }}
        path: app/build/app/outputs/flutter-apk/app-release.apk
        
    - name: Create Release (if manual trigger)
      if: github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.version.outputs.tag }}
        name: Release ${{ steps.version.outputs.tag }}
        body: |
          **Commit Message:** ${{ steps.commit.outputs.message }}
          **Version:** ${{ steps.version.outputs.tag }}
          **Build Date:** ${{ steps.build_date.outputs.date }}
          
          ## Changes
          Built from commit: ${{ github.sha }}
        files: |
          app/build/app/outputs/flutter-apk/app-release.apk
        draft: false
        prerelease: false
